---
title: "Probability and Statistics Project CC01 Group 03"
output: html_notebook
---

```{r}
cpu <- read.csv("C:/Your/Path/To/The/csv/file")
cpu <- read.csv("C:/Your/Path/To/The/csv/file", header = TRUE, colClasses = c("factor", "factor", "numeric","numeric", "numeric", "numeric", "numeric", "numeric","numeric", "numeric", "numeric", "numeric", "numeric", "numeric"), fileEncoding='UTF-8-BOM')
summary(cpu)
```
Histogram plot

For Cache Memory in kilobytes
```{r}
par(mfrow=c(2,3))
hist(cpu$CACH[cpu$vendor.name=="amd"], xlab="amdahl" ,main="")
hist(cpu$CACH[cpu$vendor.name=="bur"], xlab="burroughs" ,main="")
hist(cpu$CACH[cpu$vendor.name=="c.r.d"], xlab="c.r.d" ,main="")
hist(cpu$CACH[cpu$vendor.name=="cdc"], xlab="cdc" ,main="")
hist(cpu$CACH[cpu$vendor.name=="dec"], xlab="dec" ,main="")
hist(cpu$CACH[cpu$vendor.name=="dg"], xlab="dg" ,main="")
hist(cpu$CACH[cpu$vendor.name=="hwell"], xlab="honeywell" ,main="")
hist(cpu$CACH[cpu$vendor.name=="hp"], xlab="hp" ,main="")
hist(cpu$CACH[cpu$vendor.name=="ibm"], xlab="ibm" ,main="")
hist(cpu$CACH[cpu$vendor.name=="nas"], xlab="nas" ,main="")
hist(cpu$CACH[cpu$vendor.name=="ncr"], xlab="ncr" ,main="")
hist(cpu$CACH[cpu$vendor.name=="spe"], xlab="sperry" ,main="")
```
Histogram plot

For Average memory size
```{r}
par(mfrow=c(2,3))
hist(cpu$MAVG[cpu$vendor.name=="amd"], xlab="amdahl" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="bur"], xlab="burroughs" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="c.r.d"], xlab="c.r.d" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="cdc"], xlab="cdc" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="dec"], xlab="dec" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="dg"], xlab="dg" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="hwell"], xlab="honeywell" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="hp"], xlab="hp" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="ibm"], xlab="ibm" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="nas"], xlab="nas" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="ncr"], xlab="ncr" ,main="")
hist(cpu$MAVG[cpu$vendor.name=="spe"], xlab="sperry" ,main="")
```
Histogram plot

For Channel capacity
```{r}
par(mfrow=c(2,3))
hist(cpu$CHCAP[cpu$vendor.name=="amd"], xlab="amdahl" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="bur"], xlab="burroughs" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="c.r.d"], xlab="c.r.d" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="cdc"], xlab="cdc" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="dec"], xlab="dec" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="dg"], xlab="dg" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="hwell"], xlab="honeywell" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="hp"], xlab="hp" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="ibm"], xlab="ibm" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="nas"], xlab="nas" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="ncr"], xlab="ncr" ,main="")
hist(cpu$CHCAP[cpu$vendor.name=="spe"], xlab="sperry" ,main="")

```
Histogram plot

For Published relative performance
```{r}
par(mfrow=c(2,3))
hist(cpu$PRP[cpu$vendor.name=="amd"], xlab="amdahl" ,main="")
hist(cpu$PRP[cpu$vendor.name=="bur"], xlab="burroughs" ,main="")
hist(cpu$PRP[cpu$vendor.name=="c.r.d"], xlab="c.r.d" ,main="")
hist(cpu$PRP[cpu$vendor.name=="cdc"], xlab="cdc" ,main="")
hist(cpu$PRP[cpu$vendor.name=="dec"], xlab="dec" ,main="")
hist(cpu$PRP[cpu$vendor.name=="dg"], xlab="dg" ,main="")
hist(cpu$PRP[cpu$vendor.name=="hwell"], xlab="honeywell" ,main="")
hist(cpu$PRP[cpu$vendor.name=="hp"], xlab="hp" ,main="")
hist(cpu$PRP[cpu$vendor.name=="ibm"], xlab="ibm" ,main="")
hist(cpu$PRP[cpu$vendor.name=="nas"], xlab="nas" ,main="")
hist(cpu$PRP[cpu$vendor.name=="ncr"], xlab="ncr" ,main="")
hist(cpu$PRP[cpu$vendor.name=="spe"], xlab="sperry" ,main="")
```
Box Plot 
```{r}
boxplot(CACH~vendor.name, data=cpu , col=blues9)
boxplot(PRP~vendor.name, data=cpu , col=blues9)
boxplot(MAVG~vendor.name, data=cpu , col=blues9)
boxplot(CHCAP~vendor.name, data=cpu , col=blues9)
```
PAIR PLOT MODEL
```{r}
library(ggplot2)
library(GGally)
data <- data.frame(cpu$CACH, cpu$MAVG, cpu$CHCAP, cpu$PRP)
ggpairs(data = data, lower=list(continuous="smooth", wrap=c(colour="blue")),
upper=list(wrap=list(corSize=6)), axisLabels='show')
```
ANOVA TEST
```{r}
CACH.aov= aov(CACH~vendor.name, data = cpu)
summary(CACH.aov)
```
```{r}
MAVG.aov= aov(MAVG~vendor.name, data = cpu)
summary(MAVG.aov)
```
```{r}
CHCAP.aov= aov(CHCAP~vendor.name, data = cpu)
summary(CHCAP.aov)
```
```{r}
PRP.aov= aov(PRP~vendor.name, data = cpu)
summary(PRP.aov)
```
TUKEY TEST
```{r}
TukeyHSD(CACH.aov)
```
```{r}
TukeyHSD(MAVG.aov)
```
```{r}
TukeyHSD(CHCAP.aov)
```
```{r}
TukeyHSD(PRP.aov)
```
Multiple Linear Regression
```{r}
model <- lm(SQRPERF ~ MAVG + CACH + CHCAP,data = cpu)
summary(model)
```
